repos:
-   repo: https://github.com/koalaman/shellcheck-precommit
    rev: v0.9.0
    hooks:
    -   id: shellcheck
        files: ^bin/
        args: ["--severity=warning"]

-   repo: https://github.com/scop/pre-commit-shfmt
    rev: v3.7.0-1
    hooks:
    -   id: shfmt
        files: ^bin/
        args: ["-i", "4", "-ci", "-bn"]

-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    -   id: check-executables-have-shebangs
        files: ^bin/
    -   id: check-shebang-scripts-are-executable
        files: ^bin/
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
