@startuml
!include <C4/C4_Component>

rectangle "Clean Architecture Layers" {
    component "Infrastructure\n(Repos, Services)" as infra #LightGreen

    package "Applications" as apps #LightYellow {
        component "Application\n(Use Cases)" as app
    }

    component "DI Container\n(configures infrastructure dependencies)" as di #LightCyan
    component "Domain\n(Models, Protocols, Use Cases)" as domain #Orange
}

infra -down-> domain : implements protocols
app -down-> domain : uses protocols
di -down-> infra : configures
app -down-> di : depends on


note right of app
  This code interacts with users
  or does work on their behalf.
  Includes CLI, API, and Workers.
  Usecases become app features.
end note

note right of di
  Processes the configuration,
  wires everything together.
  Leverages abstraction to
  protect apps, agnostic to
  implementation details.
end note

note right of infra
  Code that is world-sullied.
  Interacts with network, disk, and external systems.
  Scope is explicitly defined by protocols.
end note

note right of domain
  Abstract definition of business.
  No dependency on other layers, but they all depnd on it.
end note

@enduml
