#+TODO: TODO WIP | DONE CANCELLED
* TODO SME
- macro-service appliance
- optimised to minimise deployment complexity

The idea is to judiciously import code from the other components,
then cobble together a django/celery wrapper,
resulting in a 4 component architecture:
- django stack web component
- celery component
- a single DB and queue

The benefit is to allow a Small to Medium Enterprises (SME)
to run their own proprietary julee service on their own infrastructure,
without depending on any 3rd parties.

It's not designed for "hyper-scale",
and it lacks the architecture's inherent commpartmentalisation
that was designed to support a service ecosystem.
However, it does provide an independant way to maintain and run orchestrations.

It may be useful for:
 - as an escape capsule that protects plantform clients from abusive "lock in"
 - a sandpit for experimenting or maintaining configurations
 - situations where a small to medium site needs to be run offline

Note, this deployment still has a dependency on some external services
(which are also self-hostable):
- Large Language Model service
  which can be self-hosted with Meta's Llama or DeepSeek,
  or available as utility services from many providers.
- W3C VC Infrastructure
  (which can be self-hosted with VCKit)
- IDR service
