"""Use cases for sphinx_hcd.

Business logic for cross-referencing, deriving entities, and CRUD operations.
"""

# CRUD use-cases by entity type
from .accelerator import (
    CreateAcceleratorRequest,
    CreateAcceleratorResponse,
    CreateAcceleratorUseCase,
    DeleteAcceleratorRequest,
    DeleteAcceleratorResponse,
    DeleteAcceleratorUseCase,
    GetAcceleratorRequest,
    GetAcceleratorResponse,
    GetAcceleratorUseCase,
    IntegrationReferenceItem,
    ListAcceleratorsRequest,
    ListAcceleratorsResponse,
    ListAcceleratorsUseCase,
    UpdateAcceleratorRequest,
    UpdateAcceleratorResponse,
    UpdateAcceleratorUseCase,
)
from .app import (
    CreateAppRequest,
    CreateAppResponse,
    CreateAppUseCase,
    DeleteAppRequest,
    DeleteAppResponse,
    DeleteAppUseCase,
    GetAppRequest,
    GetAppResponse,
    GetAppUseCase,
    ListAppsRequest,
    ListAppsResponse,
    ListAppsUseCase,
    UpdateAppRequest,
    UpdateAppResponse,
    UpdateAppUseCase,
)
from .derive_personas import (
    derive_personas,
    derive_personas_by_app_type,
    get_apps_for_persona,
    get_epics_for_persona,
)
from .epic import (
    CreateEpicRequest,
    CreateEpicResponse,
    CreateEpicUseCase,
    DeleteEpicRequest,
    DeleteEpicResponse,
    DeleteEpicUseCase,
    GetEpicRequest,
    GetEpicResponse,
    GetEpicUseCase,
    ListEpicsRequest,
    ListEpicsResponse,
    ListEpicsUseCase,
    UpdateEpicRequest,
    UpdateEpicResponse,
    UpdateEpicUseCase,
)
from .integration import (
    CreateIntegrationRequest,
    CreateIntegrationResponse,
    CreateIntegrationUseCase,
    DeleteIntegrationRequest,
    DeleteIntegrationResponse,
    DeleteIntegrationUseCase,
    ExternalDependencyItem,
    GetIntegrationRequest,
    GetIntegrationResponse,
    GetIntegrationUseCase,
    ListIntegrationsRequest,
    ListIntegrationsResponse,
    ListIntegrationsUseCase,
    UpdateIntegrationRequest,
    UpdateIntegrationResponse,
    UpdateIntegrationUseCase,
)
from .journey import (
    CreateJourneyRequest,
    CreateJourneyResponse,
    CreateJourneyUseCase,
    DeleteJourneyRequest,
    DeleteJourneyResponse,
    DeleteJourneyUseCase,
    GetJourneyRequest,
    GetJourneyResponse,
    GetJourneyUseCase,
    JourneyStepItem,
    ListJourneysRequest,
    ListJourneysResponse,
    ListJourneysUseCase,
    UpdateJourneyRequest,
    UpdateJourneyResponse,
    UpdateJourneyUseCase,
)
from .persona import (
    CreatePersonaRequest,
    CreatePersonaResponse,
    CreatePersonaUseCase,
    DeletePersonaRequest,
    DeletePersonaResponse,
    DeletePersonaUseCase,
    GetPersonaBySlugRequest,
    GetPersonaBySlugResponse,
    GetPersonaBySlugUseCase,
    ListPersonasRequest,
    ListPersonasResponse,
    ListPersonasUseCase,
    UpdatePersonaRequest,
    UpdatePersonaResponse,
    UpdatePersonaUseCase,
)

# Query use-cases
from .queries import (
    DerivePersonasRequest,
    DerivePersonasResponse,
    DerivePersonasUseCase,
    GetPersonaRequest,
    GetPersonaResponse,
    GetPersonaUseCase,
    ValidateAcceleratorsRequest,
    ValidateAcceleratorsResponse,
    ValidateAcceleratorsUseCase,
)
from .resolve_accelerator_references import (
    get_accelerator_cross_references,
    get_apps_for_accelerator,
    get_code_info_for_accelerator,
    get_dependent_accelerators,
    get_fed_by_accelerators,
    get_journeys_for_accelerator,
    get_publish_integrations,
    get_source_integrations,
    get_stories_for_accelerator,
)
from .resolve_app_references import (
    get_app_cross_references,
    get_epics_for_app,
    get_journeys_for_app,
    get_personas_for_app,
    get_stories_for_app,
)
from .resolve_story_references import (
    get_epics_for_story,
    get_journeys_for_story,
    get_related_stories,
    get_story_cross_references,
)
from .story import (
    CreateStoryRequest,
    CreateStoryResponse,
    CreateStoryUseCase,
    DeleteStoryRequest,
    DeleteStoryResponse,
    DeleteStoryUseCase,
    GetStoryRequest,
    GetStoryResponse,
    GetStoryUseCase,
    ListStoriesRequest,
    ListStoriesResponse,
    ListStoriesUseCase,
    UpdateStoryRequest,
    UpdateStoryResponse,
    UpdateStoryUseCase,
)

__all__ = [
    # Accelerator CRUD
    "CreateAcceleratorRequest",
    "CreateAcceleratorResponse",
    "CreateAcceleratorUseCase",
    "DeleteAcceleratorRequest",
    "DeleteAcceleratorResponse",
    "DeleteAcceleratorUseCase",
    "GetAcceleratorRequest",
    "GetAcceleratorResponse",
    "GetAcceleratorUseCase",
    "IntegrationReferenceItem",
    "ListAcceleratorsRequest",
    "ListAcceleratorsResponse",
    "ListAcceleratorsUseCase",
    "UpdateAcceleratorRequest",
    "UpdateAcceleratorResponse",
    "UpdateAcceleratorUseCase",
    # App CRUD
    "CreateAppRequest",
    "CreateAppResponse",
    "CreateAppUseCase",
    "DeleteAppRequest",
    "DeleteAppResponse",
    "DeleteAppUseCase",
    "GetAppRequest",
    "GetAppResponse",
    "GetAppUseCase",
    "ListAppsRequest",
    "ListAppsResponse",
    "ListAppsUseCase",
    "UpdateAppRequest",
    "UpdateAppResponse",
    "UpdateAppUseCase",
    # Epic CRUD
    "CreateEpicRequest",
    "CreateEpicResponse",
    "CreateEpicUseCase",
    "DeleteEpicRequest",
    "DeleteEpicResponse",
    "DeleteEpicUseCase",
    "GetEpicRequest",
    "GetEpicResponse",
    "GetEpicUseCase",
    "ListEpicsRequest",
    "ListEpicsResponse",
    "ListEpicsUseCase",
    "UpdateEpicRequest",
    "UpdateEpicResponse",
    "UpdateEpicUseCase",
    # Integration CRUD
    "CreateIntegrationRequest",
    "CreateIntegrationResponse",
    "CreateIntegrationUseCase",
    "DeleteIntegrationRequest",
    "DeleteIntegrationResponse",
    "DeleteIntegrationUseCase",
    "ExternalDependencyItem",
    "GetIntegrationRequest",
    "GetIntegrationResponse",
    "GetIntegrationUseCase",
    "ListIntegrationsRequest",
    "ListIntegrationsResponse",
    "ListIntegrationsUseCase",
    "UpdateIntegrationRequest",
    "UpdateIntegrationResponse",
    "UpdateIntegrationUseCase",
    # Journey CRUD
    "CreateJourneyRequest",
    "CreateJourneyResponse",
    "CreateJourneyUseCase",
    "DeleteJourneyRequest",
    "DeleteJourneyResponse",
    "DeleteJourneyUseCase",
    "GetJourneyRequest",
    "GetJourneyResponse",
    "GetJourneyUseCase",
    "JourneyStepItem",
    "ListJourneysRequest",
    "ListJourneysResponse",
    "ListJourneysUseCase",
    "UpdateJourneyRequest",
    "UpdateJourneyResponse",
    "UpdateJourneyUseCase",
    # Persona CRUD
    "CreatePersonaRequest",
    "CreatePersonaResponse",
    "CreatePersonaUseCase",
    "DeletePersonaRequest",
    "DeletePersonaResponse",
    "DeletePersonaUseCase",
    "GetPersonaBySlugRequest",
    "GetPersonaBySlugResponse",
    "GetPersonaBySlugUseCase",
    "ListPersonasRequest",
    "ListPersonasResponse",
    "ListPersonasUseCase",
    "UpdatePersonaRequest",
    "UpdatePersonaResponse",
    "UpdatePersonaUseCase",
    # Story CRUD
    "CreateStoryRequest",
    "CreateStoryResponse",
    "CreateStoryUseCase",
    "DeleteStoryRequest",
    "DeleteStoryResponse",
    "DeleteStoryUseCase",
    "GetStoryRequest",
    "GetStoryResponse",
    "GetStoryUseCase",
    "ListStoriesRequest",
    "ListStoriesResponse",
    "ListStoriesUseCase",
    "UpdateStoryRequest",
    "UpdateStoryResponse",
    "UpdateStoryUseCase",
    # Query use-cases
    "DerivePersonasRequest",
    "DerivePersonasResponse",
    "DerivePersonasUseCase",
    "GetPersonaRequest",
    "GetPersonaResponse",
    "GetPersonaUseCase",
    "ValidateAcceleratorsRequest",
    "ValidateAcceleratorsResponse",
    "ValidateAcceleratorsUseCase",
    # Persona derivation functions
    "derive_personas",
    "derive_personas_by_app_type",
    "get_apps_for_persona",
    "get_epics_for_persona",
    # Story references
    "get_epics_for_story",
    "get_journeys_for_story",
    "get_related_stories",
    "get_story_cross_references",
    # App references
    "get_app_cross_references",
    "get_epics_for_app",
    "get_journeys_for_app",
    "get_personas_for_app",
    "get_stories_for_app",
    # Accelerator references
    "get_accelerator_cross_references",
    "get_apps_for_accelerator",
    "get_code_info_for_accelerator",
    "get_dependent_accelerators",
    "get_fed_by_accelerators",
    "get_journeys_for_accelerator",
    "get_publish_integrations",
    "get_source_integrations",
    "get_stories_for_accelerator",
]
